version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: sneaker_store_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: sneaker_store
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - sneaker_network

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    container_name: sneaker_store_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/sneaker_store?authSource=admin
    depends_on:
      - mongodb
    networks:
      - sneaker_network
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: sneaker_store_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - sneaker_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  sneaker_network:
    driver: bridge